CREATE TABLE CUSTOMER (
	CUS_ID INT PRIMARY KEY NOT NULL,
    CUS_FNAME VARCHAR(15) not null,
    CUS_LNAME VARCHAR(15) not null,
    CUS_PHONE VARCHAR(12) not null
);

CREATE TABLE ITEM (
	ITEM_NUM INT PRIMARY KEY NOT NULL,
    CUS_ID INT UNIQUE NOT NULL,
    ITEM_PRICE DECIMAL(10,2),
    ITEM_PURCH_DATE DATE,
    ITEM_DESCRIPTION VARCHAR(255),
    FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER (CUS_ID),
    CONSTRAINT PRICE_CHK CHECK (ITEM_PRICE >= 0)
);

CREATE TABLE COMPANY (
	COMPANY_ID INT PRIMARY KEY NOT NULL,
    ITEM_NUM INT NOT NULL,
    COMPANY_NAME VARCHAR(25) UNIQUE,
    COMPANY_ADDRESS VARCHAR(25),
    COMPANY_CITY VARCHAR(25),
    COMPANY_STATE VARCHAR(25),
    COMAPNY_ZIP VARCHAR(10),
    FOREIGN KEY (ITEM_NUM) REFERENCES ITEM (ITEM_NUM)
);