-- this file inserts data into the given tables
INSERT INTO CUSTOMER (CUS_ID , CUS_FNAME , CUS_LNAME , CUS_PHONE ) VALUES 
(NULL, "John", "Smith", "615-987-1356");
INSERT INTO CUSTOMER (CUS_ID , CUS_FNAME , CUS_LNAME , CUS_PHONE ) VALUES 
(NULL, "Jane", "Sully", "615-988-1234");
INSERT INTO CUSTOMER (CUS_ID , CUS_FNAME , CUS_LNAME , CUS_PHONE ) VALUES 
(NULL, "Mary", "Jane", "615-927-2368");
INSERT INTO CUSTOMER (CUS_ID , CUS_FNAME , CUS_LNAME , CUS_PHONE ) VALUES 
(NULL, "Yassaman", "Yolo", "615-857-6781");
INSERT INTO CUSTOMER (CUS_ID , CUS_FNAME , CUS_LNAME , CUS_PHONE ) VALUES 
(NULL, "Kim", "Kardy", "615-657-5529");
INSERT INTO CUSTOMER (CUS_ID , CUS_FNAME , CUS_LNAME , CUS_PHONE ) VALUES 
(NULL, "Fairie", "Fly", "615-954-4589");
INSERT INTO CUSTOMER (CUS_ID , CUS_FNAME , CUS_LNAME , CUS_PHONE ) VALUES 
(NULL, "Jake", "StateFarm", "615-986-1582");
INSERT INTO CUSTOMER (CUS_ID , CUS_FNAME , CUS_LNAME , CUS_PHONE ) VALUES 
(NULL, "Sandy", "Claws", "615-988-2367");
INSERT INTO CUSTOMER (CUS_ID , CUS_FNAME , CUS_LNAME , CUS_PHONE ) VALUES 
(NULL, "Jack", "Skellington", "615-427-6548");
INSERT INTO CUSTOMER (CUS_ID , CUS_FNAME , CUS_LNAME , CUS_PHONE ) VALUES 
(NULL, "Aqua", "Fina", "615-403-1892");

INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1230, 1, 122.99, "SINGLE KAYAK W/ PADDLE");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1231, 2, 14.59, "WOMENS TEE SHIRT - BLACK");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1232, 3, 19.88, "OTTERBOX IPHONE 13 PRO CASE - CLEAR");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1233, 4, 12.97, "TIDE DETERGENT - LAVENDER");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1234, 5, 10.68, "SCOTTS TOILET PAPER - 12 ROLLS");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1235, 6, 10.17, "WEEKLY/MONTHLY PLANNER 2022-2023");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1236, 7, 21.99, "LAPTOP STAND FOR DESK");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1237, 8, 14.99, "MENS BELT - BROWN");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1238, 9, 7.48, "DIGIORNOS FROZEN PIZZA - PEPPERONI");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1239, 9, 3.98, "FROZEN CURLY FRIES");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1240, 10, 98.99, "MOUNTAIN BIKE - 24 INCH WHEELS");

-- manually adding more purchases to customers
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1235, 2, 10.17, "WEEKLY/MONTHLY PLANNER 2022-2023");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1236, 3, 21.99, "LAPTOP STAND FOR DESK");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1237, 6, 14.99, "MENS BELT - BROWN");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1238, 2, 7.48, "DIGIORNOS FROZEN PIZZA - PEPPERONI");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1239, 5, 3.98, "FROZEN CURLY FRIES");
INSERT INTO ITEM (ITEM_NUM, CUS_ID, ITEM_PRICE, ITEM_DESCRIPTION) VALUES
(1240, 8, 98.99, "MOUNTAIN BIKE - 24 INCH WHEELS");



INSERT INTO COMPANY (COMPANY_ID, ITEM_NUM, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_CITY, COMPANY_STATE, COMPANY_ZIP) VALUES
(101, 01230, "RAFTIEZ", "8822 Beacon Ave.", "Kaukauna", "WI", 54130);
INSERT INTO COMPANY (COMPANY_ID, ITEM_NUM, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_CITY, COMPANY_STATE, COMPANY_ZIP) VALUES
(102, 01231, "TEE OUTLET", "48 Green Hill Dr.", "Levittown", "NY", 11756);
INSERT INTO COMPANY (COMPANY_ID, ITEM_NUM, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_CITY, COMPANY_STATE, COMPANY_ZIP) VALUES
(103, 01232, "OTTERBOX", "59 Monroe Ave.", "Arlington", "MA", 52474);
INSERT INTO COMPANY (COMPANY_ID, ITEM_NUM, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_CITY, COMPANY_STATE, COMPANY_ZIP) VALUES
(104, 01233, "TIDE", "39 Edgewater St.", "Greenwood", "SC", 29646); 
INSERT INTO COMPANY (COMPANY_ID, ITEM_NUM, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_CITY, COMPANY_STATE, COMPANY_ZIP) VALUES
(105, 01234, "SCOTTS", "8014 Madison Dr.", "Shepherdsville","KY",40165); 
INSERT INTO COMPANY (COMPANY_ID, ITEM_NUM, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_CITY, COMPANY_STATE, COMPANY_ZIP) VALUES
(106, 01235, "PLAN AHEAD", "9286 Johnson Dr.", "San Pablo", "CA", 94806); 
INSERT INTO COMPANY (COMPANY_ID, ITEM_NUM, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_CITY, COMPANY_STATE, COMPANY_ZIP) VALUES
(107, 01236, "STAND UP", "421 East School Ave.", "Morton Grove", "IL", 60053); 
INSERT INTO COMPANY (COMPANY_ID, ITEM_NUM, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_CITY, COMPANY_STATE, COMPANY_ZIP) VALUES
(108, 01237, "BUCKLED", "628 Glen Eagles Ave.", "Hyde Park", "NY", 11040); 
INSERT INTO COMPANY (COMPANY_ID, ITEM_NUM, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_CITY, COMPANY_STATE, COMPANY_ZIP) VALUES
(109, 01238, "DIGIORNOS", "8718 South Ann Ct. ", "Euless", "TX", 76039); 
INSERT INTO COMPANY (COMPANY_ID, ITEM_NUM, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_CITY, COMPANY_STATE, COMPANY_ZIP) VALUES
(110, 01239, "POTATO FACTORY", "9921 Cottage Rd.", "Round", "IL", 60073); 
INSERT INTO COMPANY (COMPANY_ID, ITEM_NUM, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_CITY, COMPANY_STATE, COMPANY_ZIP) VALUES
(111, 01240, "HIKE FALLS", "884 Arcadia St.", "Randolph", "MA", 22368); 





select * from CUSTOMER;
SELECT * FROM ITEM;
SELECT * FROM COMPANY;
